#!/usr/bin/env python3

from captain2rs import dispersal_distances_threshold_rs

v = dispersal_distances_threshold_rs(2, 0.1, 3, True)
print(v)
print(v[(0,1,1,0)])
assert(v[(0,1,1,0)] == 7.213541526967138e-07)

assert(v[(5, 9, 7, 1)] == -7.3456)
